data:
  type: doppelgangers.datasets.sfm_disambiguation_dataset
  num_workers: 4
  root_dir: 'data/sfm_disambiguation/imc2024/church/images'
  test:
    batch_size: 1
    img_size: 1024
    pair_path: 'result/church/pairs_list.npy'

models:
  decoder:
    type: doppelgangers.models.cnn_classifier
    input_dim: 10